### Registrar Pedido
POST https://humble-space-computing-machine-q7pxjppw65xph46jp-8080.app.github.dev/producto/marca/1001/nuevo
Content-Type: application/json

{
 "nombre":"Joel",
"descripcion": "Joel Choquepata Guarniz",
	"precio":50,
	"stock":3
}

### Ajustar stock
POST https://humble-space-computing-machine-q7pxjppw65xph46jp-8080.app.github.dev/producto/stock/ajuste
Content-Type: application/json

{
  "idProducto": 1067,
  "stock": 3
}

### Consultar producto por id
GET https://humble-space-computing-machine-q7pxjppw65xph46jp-8080.app.github.dev/producto/1007

### Registrar pedido
POST https://humble-space-computing-machine-q7pxjppw65xph46jp-8080.app.github.dev/pedido/nuevo
Content-Type: application/json

{
 "items":[
   {
     "idProducto": 1067,
     "cantidad": 3,
     "precioUnitario":50
   }
 ]
}
### Registrar producto
POST https://humble-space-computing-machine-q7pxjppw65xph46jp-8080.app.github.dev/producto/marca/1001/nuevo
Content-Type: application/json

{
 "nombre":"Joel",
"descripcion": "Joel Choquepata Guarniz",
	"precio":50,
	"stock":3
}